/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vew;

import Model.Galerias;
import controller.ControlGalerias;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mario
 */
public class frmGalerias extends javax.swing.JInternalFrame {
    
    ControlGalerias cg=new ControlGalerias();    
    DefaultTableModel tabla=new DefaultTableModel();
    
    public void llenarTabla(){
        tabla.setColumnCount(0);
        tabla.addColumn("nombre");
        tabla.addColumn("ubicación");
        ArrayList<Galerias> lista=cg.mostrar();
        tabla.setNumRows(lista.size());
        for (int i = 0; i < lista.size(); i++) {
            tabla.setValueAt(lista.get(i).getNombreGaleria(), i, 0);
            tabla.setValueAt(lista.get(i).getUbucacionGaleria(), i, 1);
        }
        jTable1.setModel(tabla);
    }
;    /**
     * Creates new form frmGalerias
     */
    public frmGalerias() {
        initComponents();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setTitle("Gestión de Galerias");

        jToolBar2.setRollover(true);
        jToolBar2.add(jLabel1);

        getContentPane().add(jToolBar2, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
